# Generated by Django 5.2 on 2025-09-19 14:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Motorcycle Brand',
                'verbose_name_plural': 'Motorcycle Brands',
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(blank=True, max_length=100, null=True)),
                ('production_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles', to='motorcycles.motorcyclebrand')),
            ],
            options={
                'verbose_name': 'Motorcycle',
                'verbose_name_plural': 'Motorcycles',
            },
        ),
        migrations.CreateModel(
            name='MotorcyclePriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('log_date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=100)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='motorcycles.motorcycle')),
            ],
            options={
                'verbose_name': 'Motorcycle Price Log',
                'verbose_name_plural': 'Motorcycle Price Logs',
                'ordering': ['-log_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='motorcycle',
            constraint=models.UniqueConstraint(fields=('brand', 'model', 'trim', 'production_year'), name='unique_motorcycle_variant'),
        ),
        migrations.AddConstraint(
            model_name='motorcyclepricelog',
            constraint=models.UniqueConstraint(fields=('motorcycle', 'log_date', 'source'), name='price_log_per_day_per_source'),
        ),
    ]
