# Generated by Django 5.2 on 2025-09-20 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('symbol', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name_fa', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('METAL', 'Precious Metals'), ('CURRENCY', 'Currencies'), ('CRYPTO', 'Cryptocurrencies'), ('COMMODITY', 'Commodities'), ('INDEX', 'Stock Market Indices'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssetPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('change_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('change_percent', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='assets.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('asset', 'timestamp')},
            },
        ),
    ]
