# Generated by Django 5.2 on 2025-10-06 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('symbol', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name_fa', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('COIN', 'Iranian Coins'), ('CURRENCY_IRR', 'Currency in IRR'), ('CURRENCY_FX', 'Forex Rates'), ('CRYPTO_IRR', 'Crypto in IRR'), ('CRYPTO_USD', 'Crypto in USD'), ('GOLD', 'Gold Variants'), ('METAL', 'Industrial & Precious Metals'), ('COMMODITY', 'Commodities'), ('INDEX', 'Stock Market Indices'), ('DERIVATIVES', 'Futures & Options'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_monitored', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssetPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('change_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('change_percent', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='assets.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('asset', 'timestamp')},
            },
        ),
    ]
