# Generated by Django 5.2 on 2025-09-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_monitored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('COIN', 'Iranian Coins'), ('CURRENCY_IRR', 'Currency in IRR'), ('CURRENCY_FX', 'Forex Rates'), ('CRYPTO_IRR', 'Crypto in IRR'), ('CRYPTO_USD', 'Crypto in USD'), ('GOLD', 'Gold Variants'), ('METAL', 'Industrial & Precious Metals'), ('COMMODITY', 'Commodities'), ('INDEX', 'Stock Market Indices'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
