# Generated by Django 5.2 on 2025-10-06 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('visibility', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('title_fa', models.CharField(blank=True, max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'db_table': 'sellers',
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Warranty',
                'verbose_name_plural': 'Warranties',
                'db_table': 'warranties',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('api_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title_fa', models.CharField(max_length=500)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='marketable', max_length=50)),
                ('product_type', models.CharField(default='product', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('test_title_fa', models.CharField(blank=True, max_length=500, null=True)),
                ('test_title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('alternate_name', models.CharField(blank=True, max_length=500, null=True)),
                ('metric6', models.IntegerField(blank=True, null=True)),
                ('dimension2', models.IntegerField(blank=True, null=True)),
                ('dimension6', models.IntegerField(blank=True, null=True)),
                ('dimension7', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension9', models.FloatField(blank=True, null=True)),
                ('dimension11', models.IntegerField(blank=True, null=True)),
                ('dimension20', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_rate', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('review_rating_value', models.IntegerField(blank=True, null=True)),
                ('review_author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('review_date_published', models.DateField(blank=True, null=True)),
                ('review_body', models.TextField(blank=True, null=True)),
                ('digiplus_services', models.JSONField(default=list)),
                ('digiplus_service_list', models.JSONField(default=list)),
                ('digiplus_services_summary', models.JSONField(default=list)),
                ('is_jet_eligible', models.BooleanField(default=False)),
                ('is_general_location_jet_eligible', models.BooleanField(default=False)),
                ('fast_shipping_text', models.TextField(blank=True, null=True)),
                ('mpn', models.CharField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('price_currency', models.CharField(default='IRR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_fetched_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobiles', to='mobiles.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobiles', to='mobiles.category')),
            ],
            options={
                'verbose_name': 'Mobile',
                'verbose_name_plural': 'Mobiles',
                'db_table': 'mobiles',
            },
        ),
        migrations.CreateModel(
            name='MobileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('webp_url', models.URLField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mobiles.mobile')),
            ],
            options={
                'verbose_name': 'Mobile Image',
                'verbose_name_plural': 'Mobile Images',
                'db_table': 'mobile_images',
                'ordering': ['-is_main', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(max_length=500)),
                ('value_fa', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='mobiles.mobile')),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specifications',
                'db_table': 'specifications',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(unique=True)),
                ('selling_price', models.PositiveIntegerField()),
                ('rrp_price', models.PositiveIntegerField(blank=True, null=True)),
                ('order_limit', models.PositiveIntegerField(default=1)),
                ('is_incredible', models.BooleanField(default=False)),
                ('availability', models.CharField(default='https://schema.org/InStock', max_length=100)),
                ('is_jet_eligible', models.BooleanField(default=False)),
                ('cash_back', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='mobiles.color')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='mobiles.mobile')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='mobiles.seller')),
                ('warranty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='mobiles.warranty')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
                'db_table': 'variants',
            },
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['brand', 'rating_rate'], name='mobiles_brand_i_cb4217_idx'),
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['status'], name='mobiles_status_18d5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['api_fetched_at'], name='mobiles_api_fet_29bc71_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileimage',
            index=models.Index(fields=['mobile', 'url'], name='mobile_imag_mobile__bf8db8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('mobile', 'title')},
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['mobile', 'selling_price'], name='variants_mobile__4ee1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['seller'], name='variants_seller__2f0eb7_idx'),
        ),
    ]
