# Generated by Django 5.2 on 2025-10-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(help_text='The unique product ID from the API', unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated slug for clean URLs', max_length=100, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('status', models.CharField(db_index=True, default='marketable', max_length=50)),
                ('rating_rate', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('review', models.JSONField(blank=True, default=dict, help_text="Stores the 'review' object from the API")),
                ('specifications', models.JSONField(blank=True, default=dict, help_text="Stores the 'specifications' list from the API")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobiles', to='mobiles.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobiles', to='mobiles.category')),
            ],
        ),
        migrations.CreateModel(
            name='MobileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('is_main', models.BooleanField(default=False)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mobiles.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(unique=True)),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('color_name', models.CharField(blank=True, max_length=100)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('warranty_name', models.CharField(blank=True, max_length=255)),
                ('selling_price', models.PositiveIntegerField(default=0)),
                ('rrp_price', models.PositiveIntegerField(default=0)),
                ('order_limit', models.PositiveIntegerField(default=1)),
                ('is_incredible', models.BooleanField(default=False)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='mobiles.mobile')),
            ],
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['brand', 'rating_rate'], name='mobiles_mob_brand_i_57a229_idx'),
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['status'], name='mobiles_mob_status_5a3fe1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mobileimage',
            unique_together={('mobile', 'image_url')},
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('mobile', 'api_id')},
        ),
    ]
