# Generated by Django 5.2 on 2025-10-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='is_incredible',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='order_limit',
        ),
    ]
