# Generated by Django 5.2 on 2025-10-08 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_remove_variant_is_incredible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='review',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='specifications',
        ),
        migrations.AddField(
            model_name='mobile',
            name='review_description',
            field=models.TextField(blank=True, help_text="Stores the 'description' from the review object", null=True),
        ),
        migrations.CreateModel(
            name='SpecAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='mobiles.specgroup')),
            ],
            options={
                'unique_together': {('group', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ReviewAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=500)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_attributes', to='mobiles.mobile')),
            ],
            options={
                'unique_together': {('mobile', 'title')},
            },
        ),
        migrations.CreateModel(
            name='MobileSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='mobiles.mobile')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_values', to='mobiles.specattribute')),
            ],
            options={
                'unique_together': {('mobile', 'attribute')},
            },
        ),
    ]
