# Generated by Django 5.2 on 2025-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_alter_brand_api_id_alter_category_api_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mobileimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mobileimage',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mobileimage',
            name='webp_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
