# Generated by Django 5.2 on 2025-10-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_alter_brand_url_alter_mobile_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='api_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='rrp_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='selling_price',
            field=models.BigIntegerField(),
        ),
    ]
