# Generated by Django 5.2 on 2025-09-20 06:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, unique=True, verbose_name='Persian Name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='English Name')),
            ],
            options={
                'verbose_name': 'Car Brand',
                'verbose_name_plural': 'Car Brands',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_fa', models.CharField(max_length=100, verbose_name='Persian Model')),
                ('model_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='English Model')),
                ('trim_fa', models.CharField(max_length=100, verbose_name='Persian Trim')),
                ('trim_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='English Trim')),
                ('production_year', models.PositiveSmallIntegerField(verbose_name='Production Year')),
                ('specifications_fa', models.CharField(blank=True, max_length=255, verbose_name='Persian Specifications')),
                ('specifications_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Specifications')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='cars.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='Price')),
                ('log_date', models.DateField(default=django.utils.timezone.now, verbose_name='Log Date')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='cars.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Car Price Log',
                'verbose_name_plural': 'Car Price Logs',
                'ordering': ['-log_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('brand', 'model_fa', 'trim_fa', 'production_year', 'specifications_fa'), name='unique_car_variant_fa'),
        ),
        migrations.AddConstraint(
            model_name='pricelog',
            constraint=models.UniqueConstraint(fields=('vehicle', 'log_date'), name='car_price_log_per_day'),
        ),
    ]
