# Generated by Django 5.2 on 2025-10-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpecGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(help_text='The unique product ID from the API', unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated slug for clean URLs', max_length=100, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('status', models.CharField(db_index=True, default='marketable', max_length=50)),
                ('rating_rate', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('review_description', models.TextField(blank=True, help_text="Stores the 'description' from the review object", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_attributes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='products.specattribute')),
            ],
        ),
        migrations.AddField(
            model_name='specattribute',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.specgroup'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(unique=True)),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('color_name', models.CharField(blank=True, max_length=100)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('warranty_name', models.CharField(blank=True, max_length=255)),
                ('selling_price', models.PositiveIntegerField(default=0)),
                ('rrp_price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'rating_rate'], name='products_pr_brand_i_19c12f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'image_url')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewattribute',
            unique_together={('product', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('product', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='specattribute',
            unique_together={('group', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'api_id')},
        ),
    ]
